# Generated by Django 2.2.4 on 2019-08-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
